/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9300df71-dcc0-4218-83dd-760dc71c44a7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VQPwNwm1m",
    "aws_user_pools_web_client_id": "49e9sfnp1djrddiotpbmtqj9uc",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyiotlambdaapi",
            "endpoint": "https://pguxcl0mkk.execute-api.us-east-1.amazonaws.com/lambdaapp",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
