/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aed927b0-956f-44d6-a0bc-8ddf0a9fd813",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uCStaIsaZ",
    "aws_user_pools_web_client_id": "d619330paicshk4vo8o6f3m8d",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyiotlambdaapi",
            "endpoint": "https://as444ubjc2.execute-api.us-east-1.amazonaws.com/lambdatest",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
